kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      remoteWrite:
        - url: "http://sample-monitoring-stack-prometheus.monitoring-stack.svc.cluster.local:9090/api/v1/write"
          writeRelabelConfigs:
          - sourceLabels: ["namespace"]
            regex: "superheroes|monitoring-stack"
            action: keep
